### ISSUE TITLE
Package information

### ISSUE THREAD

**Issue by oriolete** [keirbowden/cliscripts#1]
Hi Bob,

I've found that you are assuming that all  metadata types except reports,dashboards,custom objects and emails use willcard but this is not true. 

Another thing I found is that in your list of metadata you're missing metadatas, f.e. documents

But your approach to extract foldered metadata via query rather than via list and describe metata is much faster.

Best regards,
Oriol

**Comment by keirbowden** [comment]
Thanks for the info - feel free to create a pull request with appropriate changes.

**Comment by oriolete** [comment]
Ok, I'll try to change that I think is wrong and create a pull request.

Best regards

**Comment by oriolete** [comment]
@keirbowden I've create a new PR with this changes:
-Added support for document metadata
-Added describe metadata command for only extract metadata in current org
